### ISSUE TITLE
Installation fails on Mac

### ISSUE THREAD

**Issue by wernerglinka** [pedelman/brackets-surround#1]
I get the following error message: The downloaded content is not a valid zip file

**Comment by pedelman** [comment]
I was looking into the problem this morning and it looks like GitHub is serving bad .zip files. You can clone the repo and manually install. 

Will look into this more later today.

**Comment by wernerglinka** [comment]
Thanks for the note Patrick. 
I downloaded several other plugins and some downloaded ok, some showed the same problem. Upon unzipping the file created has a .cpgz extension. 
Werner

On Apr 29, 2013, at 10:39 AM, Patrick Edelman wrote:

> I was looking into the problem this morning and it looks like GitHub is serving bad .zip files. You can clone the repo and manually install.
> 
> Will look into this more later today.
> 
> —
> Reply to this email directly or view it on GitHub.

werner glinka
650 851 5909
wg@wernerglinka.com
www.wernerglinka.com

**Comment by pedelman** [comment]
I just recently tested this and it appears to be working as expected currently. I just updated the README with a new path for the easy install and it should be working as expected.
