### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Cilofrapez** [pedelman/brackets-surround#11]
Hi!

I install the extension, reset brackets, check that there's a "Surround" item on Edit menu, but when I select text and use it, it asks me for the text I want to surround the selection with, and after i type for example <strong> or whatever, it just does nothing. I hit enter and the whole thing stays still there..

**Comment by rcrooks** [comment]
Same here, Surround modal comes up, but then does nothing when you enter a character and press return. I know this used to work well, so something must have broken with a recent Brackets update

**Comment by pedelman** [comment]
This has been resolved, thanks for the feedback. If you had it previously installed through the extensions registry, you can now update and it should work as intended.

**Comment by rcrooks** [comment]
Thank you!!!

___________Robert Crooks
Director of Learning Services, Brightcove
