### ISSUE TITLE
Link in Brackets installation says it's wrong....

### ISSUE THREAD

**Issue by fernamp** [pedelman/brackets-surround#2]
I didn't know where to tell you about the link for the installation of the extension... so I put it here.

I used: 
https://github.com/pedelman/brackets-surround.git

And brackets says it can't install for a 406 error.

I removed the ".git", like
https://github.com/pedelman/brackets-surround

and everything worked ok.

**Comment by pedelman** [comment]
Thanks for the feedback, fixed this up in the installation instructions.
