### ISSUE TITLE
Surround broken by something in Sprint 27 build

### ISSUE THREAD

**Issue by rcrooks** [pedelman/brackets-surround#3]
Hi,
This fabulous extension stopped working with the latest Sprint (27). The surround dialog opens, but when I type something in and press return, nothing happens. On Mac OS X Mountain Lion.

**Comment by pedelman** [comment]
Thank you for the feedback. Will try and have a fix up by later tonight.

**Comment by thefirstofthe300** [comment]
Any update on this? @pedelman

**Comment by pedelman** [comment]
Sorry guys, I've been really busy. I was able to reproduce the bug, so I just need to push up a patch once I find a solid fix.

**Comment by pedelman** [comment]
Alright, I got a new version pushed. It turns out they changed the argument in the cancelModalDialogIfOpen from a selector to the string of the modals class. Much easier fix than I had expected.

Thanks for letting me know, guys!
