### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by imbwaldo** [pedelman/brackets-surround#6]
I'm working in Sprint 39 on a Mac, and the Cmd + Shift + J doesn't appear to work anymore. Is this a problem of my own creation, or did something break in Sprint 39?

**Comment by pedelman** [comment]
Hmm I just tested on Sprint 39 and everything worked well for me. Maybe try opening up the developer console and see if there are any errors. Any steps to reproduce would be useful.

**Comment by imbwaldo** [comment]
When I did the homework I should've done before posting you, I discovered that the Emmet extension took over that keyboard shortcut. Sorry for the false alarm!

**Comment by pedelman** [comment]
Dang.. that's a bummer. If you are comfortable editing the extension, you could simply adjust what the hotkey is and run your own local version.

**Comment by imbwaldo** [comment]
Hey, you've done the heavy lifting--thanks for your extension. :) As soon as I realized there was a conflict, I started thinking about doing just that--adjusting the hotkey. I'll have a go at it.

Thanks again.

**Comment by pedelman** [comment]
Let me know if you need any help, I'm going to go ahead and close this out.
