### ISSUE TITLE
Doesn't work in Brakets 41 -  0.41.0-13418 (release e642284b3) 

### ISSUE THREAD

**Issue by processnull** [pedelman/brackets-surround#7]
I can open dialog and put the tag but can't submit when press enter key.

**Comment by soulrelic616** [comment]
I am having the same issue.

**Comment by rarebush** [comment]
I corrected the issue and made a pull request - you can fix it yourself by changing 'main.js :114' from 

$('#surround_input').keypress(function (e) {

to:

 $('#surround_input').keyup(function (e) {

**Comment by soulrelic616** [comment]
Thanks, that did it for me!

**Comment by pedelman** [comment]
This has been resolved, thanks for the feedback. If you had it previously installed through the extensions registry, you can now update and it should work as intended.
